In [3]:
import numpy as n 
import pandas as p

In [4]:
pwd

'/Users/ka53/Desktop/ml-practice/pandas'

In [5]:
import os

In [6]:
os.getcwd()

'/Users/ka53/Desktop/ml-practice/pandas'

In [ ]:
#df = p.read_csv('/Users/ka53/Desktop/ml/Notebooks ML Rus V10/DATA/example.csv')

In [9]:
df = p.read_csv('/Users/ka53/Downloads/England Football Results.csv',header=None)

In [10]:
df

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
0,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
1,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.9,2.08
2,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.9,2.2,2,1.99,1.88,2.04,1.93
3,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2,1.9,2.05,1.93,1.99,1.87,2.02,1.96
4,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.1,1.83,2.04,1.88,2.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,E0,02/11/2024,15:00,Southampton,Everton,1,0,H,0,0,...,1.95,1.98,1.93,1.99,1.98,1.99,1.94,1.94,1.99,2
97,E0,02/11/2024,17:30,Wolves,Crystal Palace,2,2,D,0,0,...,2.1,1.83,2.11,1.83,2.14,1.85,2.08,1.8,2.16,1.85
98,E0,03/11/2024,14:00,Tottenham,Aston Villa,4,1,H,0,1,...,2,1.93,2,1.93,2,1.97,1.94,1.93,2,1.98
99,E0,03/11/2024,16:30,Man United,Chelsea,1,1,D,0,0,...,1.99,1.94,2.01,1.92,2.01,1.96,1.97,1.91,2.03,1.96
100,E0,04/11/2024,20:00,Fulham,Brentford,2,1,H,0,1,...,2,1.9,2.03,1.92,2.04,1.92,2,1.86,2.05,1.94

In [11]:
df = p.read_csv('/Users/ka53/Downloads/England Football Results.csv',)

In [12]:
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,E0,02/11/2024,15:00,Southampton,Everton,1,0,H,0,0,...,1.95,1.98,1.93,1.99,1.98,1.99,1.94,1.94,1.99,2.00
96,E0,02/11/2024,17:30,Wolves,Crystal Palace,2,2,D,0,0,...,2.10,1.83,2.11,1.83,2.14,1.85,2.08,1.80,2.16,1.85
97,E0,03/11/2024,14:00,Tottenham,Aston Villa,4,1,H,0,1,...,2.00,1.93,2.00,1.93,2.00,1.97,1.94,1.93,2.00,1.98
98,E0,03/11/2024,16:30,Man United,Chelsea,1,1,D,0,0,...,1.99,1.94,2.01,1.92,2.01,1.96,1.97,1.91,2.03,1.96
99,E0,04/11/2024,20:00,Fulham,Brentford,2,1,H,0,1,...,2.00,1.90,2.03,1.92,2.04,1.92,2.00,1.86,2.05,1.94

In [13]:
df.to_csv('/Users/ka53/Desktop/new.csv') # we creat new csv file

for reading .READ_<CSV>, for creating .TO_<CSV>